### ISSUE TITLE
Why I can't listen INTERACTION_IFRAME_MODAL_CREATE message

### ISSUE THREAD

**Issue by inewlife** [LaiBaoYuan/midjourney-sdk#1]

**Comment by LaiBaoYuan** [comment]
you can see the dev branch，this bug will fix on 3.0 version

**Comment by inewlife** [comment]
Can you explain the reason? I also use websocket. I can receive other messages, but I can’t receive messages from iframe modal.

**Comment by LaiBaoYuan** [comment]
都是国人就别用英文了，你必须使用本次websocket返回的session_id作为interaction的接口请求体的sessionId的值才能接收到，因为他们的机器人只会返回本次请求接口的会话

**Comment by inewlife** [comment]
感谢，可以收到消息了，再请教下，newNonce好像没法透传

**Comment by LaiBaoYuan** [comment]
你只能自己做可视化界面，用户传递的prompt需要在后端处理，在前面拼接nonce，然后返回的content中去正则匹配它，不然没法关联上

**Comment by inewlife** [comment]
拼接字符串的话是不是可能影响提示词的效果

**Comment by LaiBaoYuan** [comment]
不会的，但也只有这种方法，他们提交任务之后的第一条create消息是没有nonce值的，这样我们就没法关联，只能content中关联

**Comment by qyyxl** [comment]
博主很强👍🏻

**Comment by qyyxl** [comment]
我有个问题请教，我看不间断的会重新建立新的ws连接，这个逻辑是什么，在什么时候放弃老的ws连接，而创建新的？

**Comment by LaiBaoYuan** [comment]
> 

现在我目前还没排查出什么问题，我也会有时候收到1006错误码的断连，国外说是因为discord那边检测到非法ip访问导致的，但是我用vpn创建连接的，但是还是会时不时发生。想问一下你的错误码是多少？

**Comment by inewlife** [comment]
我是直接部署在香港了，用的阿里云机器学习的eas，好像没遇到过断开的问题

**Comment by LaiBaoYuan** [comment]
难道还真是vpn的问题吗，我看官网他们也会时不时断掉

**Comment by qyyxl** [comment]
是的，我在discord网站上观察ws连接，也会经常需要重新创建连接，还没有看到什么错误信息

**Comment by xueyi123** [comment]
ws模式下 你们有被封号的 例子吗，我被封好好几次

**Comment by qyyxl** [comment]
还没碰到过，封了是什么提示，还有可能找回吗

**Comment by xueyi123** [comment]
找不回来
