### ISSUE TITLE
INTERACTION_IFRAME_MODAL_CREATE监听不到

### ISSUE THREAD

**Issue by weiaweiawei** [LaiBaoYuan/midjourney-sdk#2]
您好请问你下，INTERACTION_IFRAME_MODAL_CREATE 这个监听不到，是因为这部分有bug吗

**Comment by LaiBaoYuan** [comment]
不是bug啊，要用新的sseionid来请求接口，不要直接用网站上面的

**Comment by huiqiangyang** [comment]
我说我怎么也监听不到，😄

**Comment by xueyi123** [comment]
你们启动ws模式，又被封过的案例吗，我咋被封号了好几回了

**Comment by LaiBaoYuan** [comment]
没有哟

**Comment by xueyi123** [comment]
接口请求和ws不在一个ip上是不是也监听不到[INTERACTION_IFRAME_MODAL_CREATE](https://github.com/LaiBaoYuan/midjourney-sdk/issues/2#top)

**Comment by xueyi123** [comment]
我试了下，发现还是拿不到[INTERACTION_IFRAME_MODAL_CREATE] 这参数

**Comment by LaiBaoYuan** [comment]
> 接口请求和ws不在一个ip上是不是也监听不到[INTERACTION_IFRAME_MODAL_CREATE](https://github.com/LaiBaoYuan/midjourney-sdk/issues/2#top)

应该不会

**Comment by weiaweiawei** [comment]
这个ws连接的时候分配的sessionid 是不是有时间限制，一直用这个sessionid，调用sub-job接口失败

**Comment by LaiBaoYuan** [comment]
> @LaiBaoYuan 大佬，请教一下，你说的用最新session_id请求接口，这个接口是指的 [https://discord.com/api/v9/interactions这个吗，是用最新的session_id请求就会从websocket监听到INTERACTION_IFRAME_MODAL_CREATE消息了吗，我现在只能收到INTERACTION_CREATE和INTERACTION_SUCCESS](https://discord.com/api/v9/interactions%E8%BF%99%E4%B8%AA%E5%90%97%EF%BC%8C%E6%98%AF%E7%94%A8%E6%9C%80%E6%96%B0%E7%9A%84session_id%E8%AF%B7%E6%B1%82%E5%B0%B1%E4%BC%9A%E4%BB%8Ewebsocket%E7%9B%91%E5%90%AC%E5%88%B0INTERACTION_IFRAME_MODAL_CREATE%E6%B6%88%E6%81%AF%E4%BA%86%E5%90%97%EF%BC%8C%E6%88%91%E7%8E%B0%E5%9C%A8%E5%8F%AA%E8%83%BD%E6%94%B6%E5%88%B0INTERACTION_CREATE%E5%92%8CINTERACTION_SUCCESS)

session是取创建ws连接返回给你的那个，具体请看[官方文档](https://discord.com/developers/docs/topics/gateway)的生命周期，具体ws连接代码可以看[这里](https://github.com/LaiBaoYuan/midjourney-sdk/blob/master/packages/midjourney-sdk/src/ws.ts)

**Comment by lys623** [comment]
> 我试了下，发现还是拿不到[INTERACTION_IFRAME_MODAL_CREATE] 这参数

+1，换了最新的seesion_id也没收到，估计哪里还需要改下。

**Comment by lys623** [comment]
> 我试了下，发现还是拿不到[INTERACTION_IFRAME_MODAL_CREATE] 这参数

刚开始我也发现拿不到，后来发现不能去浏览器网页点按钮，要用nodejs 的ws发出Vary (Region)指令才行，然后nodejs的ws会收到INTERACTION_IFRAME_MODAL_CREATE。感谢楼主 @LaiBaoYuan li 替换最新的session_id后可以收到INTERACTION_IFRAME_MODAL_CREATE 👍解决了大难题。比较好奇，怎么发现需要使用新的seesion_id才会收到INTERACTION_IFRAME_MODAL_CREATE的 😂

**Comment by LaiBaoYuan** [comment]
> INTERACTION_IFRAME_MODAL_CREATE

不客气，我刚开始也是发现取不到，因为discord的网页点击他的ws会返回3条消息，消息内容都是加密的，我就不断的猜，最后一顿操作下来就知道啦

**Comment by lys623** [comment]
> > INTERACTION_IFRAME_MODAL_CREATE
> 
> 不客气，我刚开始也是发现取不到，因为discord的网页点击他的ws会返回3条消息，消息内容都是加密的，我就不断的猜，最后一顿操作下来就知道啦

我朋友在字节招人😂

**Comment by LaiBaoYuan** [comment]
> > > INTERACTION_IFRAME_MODAL_CREATE
> 
> > 
> 
> > 不客气，我刚开始也是发现取不到，因为discord的网页点击他的ws会返回3条消息，消息内容都是加密的，我就不断的猜，最后一顿操作下来就知道啦
> 
> 
> 
> 我朋友在字节招人😂

老哥能不能内推我哈哈哈

**Comment by LaiBaoYuan** [comment]
> > > INTERACTION_IFRAME_MODAL_CREATE
> 
> > 
> 
> > 不客气，我刚开始也是发现取不到，因为discord的网页点击他的ws会返回3条消息，消息内容都是加密的，我就不断的猜，最后一顿操作下来就知道啦
> 
> 
> 
> 我朋友在字节招人😂

准备想辞职了

**Comment by lys623** [comment]
> > > > INTERACTION_IFRAME_MODAL_CREATE
> > 
> > 
> > > 
> > 
> > 
> > > 不客气，我刚开始也是发现取不到，因为discord的网页点击他的ws会返回3条消息，消息内容都是加密的，我就不断的猜，最后一顿操作下来就知道啦
> > 
> > 
> > 我朋友在字节招人😂
> 
> 老哥能不能内推我哈哈哈

可以的，wx加起来，需要内推可以加我：lys623
