### ISSUE TITLE
大佬，可以讲解下Region的交互流程吗

### ISSUE THREAD

**Issue by huiqiangyang** [LaiBaoYuan/midjourney-sdk#3]
大佬，我请教下

我对前面怎么交互拿到 iframeId和customId 不太理解，是先调用接口，返回websocket会推送这些信息过来吗，然后组装成弹窗所需要的参数？

**Comment by LaiBaoYuan** [comment]
想收到消息，必须用自己创建的ws返回的sessionid来请求接口，然后就回返回一个iframe的customid，你可以通过这个customid以及其他的频道服务器id来组建iframe的地址，但是这个地址里面的接口很不友好，他们的后端有跨域限制，不推荐单应用，只推荐用服务端渲染来走代理拿到他们的任务图片地址，解析成base64，自己写弹窗组件提交任务。记得给个star哟！
