### ISSUE TITLE
(ce as any).clear()的位置不合适

### ISSUE THREAD

**Issue by pxz2016** [LaiBaoYuan/midjourney-sdk#6]
(ce as any).clear()的位置应该不合适，放在handleSubmit里面只能处理提交的情况，如果不提交直接关闭模态窗口的话就不行了。建议放在：inpainting-editor.tsx 里面：
 useEffect(() => {
    init()
    return () => {
      (ce as any).clear()
    }
  }, [])

**Comment by LaiBaoYuan** [comment]
确实，谢谢你的建议，我主vue技术宅的，react也是刚刚学的

**Comment by pxz2016** [comment]
你已经很厉啦，这个项目是目前我见过最牛的midjourney相关的开源项目。加油！！

**Comment by LaiBaoYuan** [comment]
一起加油！！

**Comment by LaiBaoYuan** [comment]
修复好了

**Comment by pxz2016** [comment]
请教个问题：
pnpm proxy后如何填写wss的地址，
DiscordApi's BaseUrl
https://discord.com--->http://localhost:9000/proxy/discord
DiscordWs's BaseUrl
wss://gateway.discord.gg/?encoding=json&v=9----?这个怎么填写
DiscordImage's BaseApi
https://cdn.discordapp.com--->http://localhost:9000/proxy/discordapp

**Comment by LaiBaoYuan** [comment]
ws其实是http协议的升级，直接把http换成ws就好了，ws://localhost:9000/proxy/discordWs?encoding=json&v=9

**Comment by pxz2016** [comment]
非常感谢，wss对应的是https，配置成 ws 就好了。

**Comment by LaiBaoYuan** [comment]
不客气
