### ISSUE TITLE
Vary Region Websocket

### ISSUE THREAD

**Issue by XdpCs** [LaiBaoYuan/midjourney-sdk#9]
I uses websocket in golang. 
But websocket doesn't send me the INTERACTION_IFRAME_MODAL_CREATE. 
Do you have the same problem? 
If you encountered this problem before, Can you help me?

**Comment by LaiBaoYuan** [comment]
if you don't receive the message type of "INTERACTION_IFRAME_MODAL_CREATE", you can check the sessionid parameter in the request body, the sessionid must be the returned when creating the ws connection.

**Comment by XdpCs** [comment]
OK. I will try it. Thank you!
